name: LookOut Squirrel
favicon: null
layout_spectrum: 0.5567643803078681
typography_spectrum: 0.7286027991212904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7153710452839732
  lightness: 0.023004435934126377
  saturation: 0.38701673899777234
  rhythmicContrast: 0.8157838019542396
purpose: []
