name: Look Out Squirrel
favicon: null
layout_spectrum: 0.5567643803078681
typography_spectrum: 0.7286027991212904
title: Look Out Squirrel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#64aae5'
    - '#1d2733'
    - '#aaaaaa'
    - '#395988'
    - '#7f8082'
  brandStrength: 0.7153710452839732
  lightness: 0.023004435934126377
  saturation: 0.38701673899777234
  rhythmicContrast: 0.8157838019542396
purpose: []
